import type { VocabularyWord } from "@/types/vocabulary";

// Word List 07 Data (derived from OCR of pages 26-33)
export const highSchoolUnit7: VocabularyWord[] = [
  // Page 26
  {
    word: "free",
    pronunciation: "/ friː /",
    partOfSpeech: "adj.",
    definition: "自由的;空闲的;免费的",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "Are you free this afternoon? 你今天下午有空吗？",
        "Admission to the museum is free. 博物馆免费入场。"
        ],
    usageNotes: [
        "1. for free 免费",
        "2. free of charge 免费",
        "3. set... free 释放...",
        "4. be free from/of 免受…",
        ],
  },
  {
    word: "very",
    pronunciation: "/ 'veri /",
    partOfSpeech: "adv./adj.",
    definition: "adv. 很,非常 adj. (用于加强语气)正是那个,恰是的",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "That's the very thing I've been looking for. 那正是我一直在找的东西。(adj.)",
        "She speaks English very well. 她英语说得非常好。(adv.)"
        ],
    usageNotes: [
        "Adv: In a high degree.",
        "Adj: Actual; precise (used to emphasize the identity of someone or something).",
        "the very beginning/end 最开始/最后",
        "at the very moment 就在那一刻"
        ],
  },
  {
    word: "decoration",
    pronunciation: "/ ˌdekə'reɪʃn /",
    partOfSpeech: "n.",
    definition: "装饰,修饰;装饰品",
    wordRootMemory: "Derived from 'decorate'.", // No '记' section in OCR
    examples: [
        "The girl is using some paper decorations to decorate her walls. 那个女孩子正用一些纸质装饰品在装饰她的墙壁。",
        "Christmas decorations filled the store. 商店里摆满了圣诞装饰品。"
        ],
    usageNotes: [
        "The process or art of decorating something.",
        "[C, U] A thing used to make something look more attractive.",
        "interior decoration 室内装饰",
        "cake decoration 蛋糕装饰"
        ],
    relatedWords: ["decorate(v. 装饰), decorative(adj. 装饰性的)"],
  },
  {
    word: "land",
    pronunciation: "/ lænd /",
    partOfSpeech: "n./v.",
    definition: "n. 土地;陆地 v. 登陆;(使)降落",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "dry land 旱地",
        "China has become the first country to land a spacecraft on the far side of the moon. (2020年全国卷 1)"
        ],
    usageNotes: [
        "Noun: The part of the earth's surface that is not covered by water.",
        "Verb: Put (someone or something) on shore from a boat.",
        "Verb: Come down through the air and alight on the ground or another surface (of an aircraft or spacecraft).",
        "land on... (飞机等)降落于...",
        ],
  },
  {
    word: "flame",
    pronunciation: "/ fleɪm /",
    partOfSpeech: "n.",
    definition: "火焰",
    wordRootMemory: "词根记忆:flam(燃烧; 火焰)+e→火焰",
    examples: [
        "The sticks burst into flames. 木柴很快烧了起来。",
        "The candle flame flickered in the wind. 烛火在风中摇曳。"
        ],
    usageNotes: [
        "A hot glowing body of ignited gas that is generated by something on fire.",
        "burst into flames 突然烧起来",
        "old flame 旧情人 (idiom)"
        ],
    relatedWords: ["flammable(adj. 易燃的)"],
  },
  {
    word: "jungle",
    pronunciation: "/ 'dʒʌŋgl /",
    partOfSpeech: "n.",
    definition: "丛林,密林",
    wordRootMemory: "发音记忆:“长高”→树木参天→丛林",
    examples: [
        "There are many poisonous snakes in the jungle. 丛林里有许多毒蛇。",
        "They spent a week trekking through the jungle. 他们花了一周时间徒步穿越丛林。"
        ],
    usageNotes: [
        "An area of land overgrown with dense forest and tangled vegetation, typically in the tropics.",
        "concrete jungle (喻)钢筋水泥丛林，无生气的大都市",
        "the law of the jungle 丛林法则"
        ],
  },
  {
    word: "political",
    pronunciation: "/ pə'lɪtɪkl /",
    partOfSpeech: "adj.",
    definition: "政治的",
    wordRootMemory: "联想记忆:和 politics(n. 政治)一起记",
    examples: [
        "He is a political leader. 他是一名政治领袖。",
        "The country is facing a period of political instability. 该国正面临一段政治动荡时期。"
        ],
    usageNotes: [
        "Relating to the government or public affairs of a country.",
        "political party 政党",
        "political system 政治体制",
        "political views 政治观点"
        ],
    relatedWords: ["politician(n. 政治家,政客); politics(n. 政治;政治学)"],
  },
  {
    word: "elect",
    pronunciation: "/ ɪ'lekt /",
    partOfSpeech: "vt.",
    definition: "(投票)选举",
    wordRootMemory: "词根记忆:e(出)+lect(选择)→(投票)选举",
    examples: [
        "After Lincoln was elected President of the US in 1861, they rented the house... (2021年浙江卷)",
        "The people will elect a new government next year. 人民明年将选举新政府。"
        ],
    usageNotes: [
        "Choose (someone) to hold public office or some other position by voting.",
        "elect sb (as) + position (e.g., elect him president)",
        "elect to do sth (formal): choose to do sth"
        ],
    relatedWords: ["elected(adj.当选的); election(n. 选举)"],
  },

  // Page 27
  {
    word: "bit",
    pronunciation: "/ bɪt /",
    partOfSpeech: "n.",
    definition: "一点,一些,少量",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "The box is a bit heavy. 这个箱子有点重。",
        "I have a bit of money with me. 我随身带了一点钱。"
        ],
    usageNotes: [
        "1. a bit of 一点,一些 (修饰不可数名词)",
        "2. bit by bit 一点一点地",
        "3. not a bit 一点也不",
        "4. 'a bit' functions as an adverb modifying adj/adv/verb; contrast 'a little'."
        ],
  },
  {
    word: "fasten",
    pronunciation: "/ 'fɑːsn /",
    partOfSpeech: "v.",
    definition: "扎牢,扣住",
    wordRootMemory: "词根记忆: fast(牢的,紧的)+en(使…)→使紧,使牢固→扎牢",
    examples: [
        "Please fasten your seat belt. 请系好您的安全带。",
        "She fastened the buttons on her coat. 她扣上了大衣的纽扣。"
        ],
    usageNotes: [
        "Close or join securely.",
        "Fix or hold in place.",
        "fasten sth to sth 把某物固定在某物上"
        ],
  },
  {
    word: "journey",
    pronunciation: "/ 'dʒɜːni /",
    partOfSpeech: "n.",
    definition: "旅行,旅程",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "The journey around the world took the old sailor nine months. 老水手用9个月的时间完成了环球旅行。",
        "How long is your journey to work? 你上班的路程有多长？"
        ],
    usageNotes: [
        "An act of travelling from one place to another.",
        "Often implies a relatively long distance.",
        "Compare: journey, travel, trip, tour.",
        "go on a journey 去旅行"
        ],
  },
  {
    word: "gay",
    pronunciation: "/ geɪ /",
    partOfSpeech: "adj.",
    definition: "快活的,愉快的; (指人) 同性恋的",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "The children were all gay at the thought of the coming holidays. 孩子们一想到即将来临的假日,都很高兴。",
        "He came out as gay to his family last year. 他去年向家人出柜了。"
        ],
    usageNotes: [
        "Light-hearted and carefree. (less common modern use)",
        "Relating to or characterized by sexual or romantic attraction to people of one's own sex.",
        "The term 'happy' or 'cheerful' is more common for the first meaning now."
        ],
  },
  {
    word: "lie",
    pronunciation: "/ laɪ /",
    partOfSpeech: "n./vi./vt.",
    definition: "n. 谎言 vi. (lay, lain, lying) 躺,卧;平放;位于 vt. (lied, lied, lying) 说谎",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "The newspaper is lying next to the bed. 报纸在床旁边。(vi. 位于)",
        "Lie still and don't make any noise. 躺着别动,也不要发出任何声音。(vi. 躺)"
        ],
    usageNotes: [
        "1. lie (lay, lain, lying): be in or assume a horizontal position.",
        "2. lie (lied, lied, lying): tell an untruth.",
        "3. a white lie 善意的谎言",
        "4. lie down 躺下; lie in 存在于",
        ],
    relatedWords: ["liar (n. 说谎者)"],
  },
  {
    word: "hardship",
    pronunciation: "/ 'hɑːdʃɪp /",
    partOfSpeech: "n.",
    definition: "困难,艰辛",
    wordRootMemory: "联想记忆: hard(艰苦的)+ship(状态)→同舟共济渡难关→困难",
    examples: [
        "The novel shows the hardship of her childhood. 小说讲述了她童年时期的艰苦生活。",
        "Many people suffered severe economic hardship during the recession. 许多人在经济衰退期间遭受了严重的经济困难。"
        ],
    usageNotes: [
        "[C, U] Severe suffering or privation.",
        "face/endure hardship 面临/忍受困苦",
        "economic hardship 经济困难"
        ],
    relatedWords: ["hard(adj./adv. 困难的；努力地)"],
  },
  {
    word: "merciful",
    pronunciation: "/ 'mɜːsɪfl /",
    partOfSpeech: "adj.",
    definition: "仁慈的;宽大的",
    wordRootMemory: "Derived from 'mercy'.", // No '记' section in OCR
    examples: [
        "The merciful king set the prisoner free at the end of the story. 故事的最后,仁慈的国王释放了那个囚犯。",
        "It was merciful that the accident wasn't worse. 幸好事故没有更严重，真是万幸。"
        ],
    usageNotes: [
        "Showing mercy or compassion.",
        "Bringing someone relief from suffering.",
        "be merciful to sb 对某人仁慈"
        ],
    relatedWords: ["mercy(n. 仁慈), merciless(adj. 无情的)"],
  },
  {
    word: "immigration",
    pronunciation: "/ ˌɪmɪ'greɪʃn /",
    partOfSpeech: "n.",
    definition: "移民,移居",
    wordRootMemory: "词根记忆:im(向内)+migrat(e)(移居)+ion(表名词)→移民",
    examples: [
        "There are strict controls on immigration into this country. 这个国家对移民有严格的限制。", // Example from p28
        "Immigration has had a significant impact on the country's culture. 移民对该国的文化产生了重大影响。"
        ],
    usageNotes: [
        "The action of coming to live permanently in a foreign country.",
        "immigration laws/policy 移民法律/政策",
        "immigration officer 移民官"
        ],
    relatedWords: ["immigrate(v. 移入), immigrant(n. 移民), emigration(n. 移出)"],
  },

  // Page 28
  {
    word: "bend",
    pronunciation: "/ bend /",
    partOfSpeech: "v.",
    definition: "(bent, bent, bending) 弯曲;弯腰,屈身",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "Bend your arms and touch your shoulders. 曲臂触摸双肩。",
        "He bent over the sink to do the dishes. 他弯下腰在水槽里面洗碗。"
        ],
    usageNotes: [
        "Shape or force (something straight) into a curve or angle.",
        "(Of a person) incline the body downwards from the vertical.",
        "bend the rules 通融规定"
        ],
    relatedWords: ["bent(adj.弯的)"],
  },
  {
    word: "lame",
    pronunciation: "/ leɪm /",
    partOfSpeech: "adj.",
    definition: "跛的,残废的,瘸的",
    wordRootMemory: "发音记忆:“累母”→孩子瘸了,做母亲的当然累了",
    examples: [
        "He became lame after the accident. 他在事故后瘸了。",
        "That's a lame excuse. 那是个站不住脚的借口。(figurative)"
        ],
    usageNotes: [
        "(Of a person or animal) unable to walk normally because of injury or illness affecting the leg or foot.",
        "(Of an excuse or argument) unconvincingly feeble.",
        ],
  },
  {
    word: "cycle",
    pronunciation: "/ 'saɪkl /",
    partOfSpeech: "n./vi./vt.",
    definition: "n. 周期;循环 vi. 骑自行车;循环 vt. 使循环",
    wordRootMemory: "词根记忆:cycl(环)+e→循环",
    examples: [
        "a wave cycle 波动周期 (n.)",
        "I cannot cycle to school today because my bike is broken. 今天我不能骑车上学,因为我的车坏了。(vi.)"
        ],
    usageNotes: [
        "Noun: A series of events that are regularly repeated in the same order.",
        "Verb: Ride a bicycle.",
        "Verb: Move in or follow a cycle.",
        "life cycle 生命周期"
        ],
    relatedWords: ["bicycle(n. 自行车); recycle(vt. 回收); tricycle(n. 三轮车); cyclist(n. 骑自行车的人)"],
  },
  {
    word: "impression",
    pronunciation: "/ ɪm'preʃn /",
    partOfSpeech: "n.",
    definition: "印象,感觉",
    wordRootMemory: "词根记忆:im(进入)+press(挤压)+ion(表名词)→压进去→印象",
    examples: [
        "Sara leaves a favourable impression on the interviewer. 萨拉给面试官留下了一个好印象。",
        "What was your first impression of the city? 你对这座城市的最初印象如何？"
        ],
    usageNotes: [
        "An idea, feeling, or opinion about something or someone.",
        "An imitation of a person or thing, done to entertain.",
        "make a good/bad impression on sb 给某人留下好/坏印象",
        "be under the impression that... 以为…"
        ],
    relatedWords: ["impress(v. 使印象深刻), impressive(adj. 给人深刻印象的)"],
  },
  {
    word: "annoy",
    pronunciation: "/ ə'nɔɪ /",
    partOfSpeech: "vt.",
    definition: "使烦恼,使生气;骚扰",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "John's little brother annoyed him by changing the TV channels. 约翰的弟弟总是换台,弄得他很烦。",
        "It annoys me when people talk loudly on the phone. 人们在电话里大声说话让我很烦。"
        ],
    usageNotes: [
        "Irritate (someone); make (someone) a little angry.",
        "be annoyed at/with sb/sth 对某人/某事生气"
        ],
    relatedWords: ["annoyance(n. 烦恼 ); annoying(adj. 烦人的); annoyingly(adv. 烦人地)"],
  },
  {
    word: "mind",
    pronunciation: "/ maɪnd /",
    partOfSpeech: "n./v.",
    definition: "n. 思想 v. 介意",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "He doesn't mind lending you his dictionary. 他不介意把词典借给你。(v.)",
        "Do you mind if I sit here? 你介意我坐在这儿吗?(v.)"
        ],
    usageNotes: [
        "1. mind + doing 介意(做)…",
        "2. Do/Would you mind + doing...?/if...? (用于请求)",
        "3. Response: 'Of course not./Not at all./No, please.' (不介意); 'I'm sorry but I do.' (介意)",
        "4. keep... in mind 把…记在心上; make up one's mind 下定决心",
        ],
  },

  // Page 29
  {
    word: "hatch",
    pronunciation: "/ hætʃ /",
    partOfSpeech: "vi./vt.",
    definition: "vi. (小鸟、小鸡等)出壳;(蛋)破壳,孵化 vt. 使(小鸟、小鸡等)孵出",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "Nearly all eggs have hatched. 几乎所有的蛋都孵出了小鸡。",
        "The birds hatched their eggs in the nest. 鸟儿在巢里孵蛋。"
        ],
    usageNotes: [
        "(Of an egg) open and produce a young animal.",
        "(Of a young animal) emerge from an egg.",
        "Conspire to devise (a plot or plan).",
        "hatch a plan/plot 策划阴谋"
        ],
  },
  {
    word: "die",
    pronunciation: "/ daɪ /",
    partOfSpeech: "vi.",
    definition: "(died, died, dying) 死亡;消失;熄灭",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "Many people die of hunger every year. 每年有许多人死于饥饿。",
        "The fire became weak and finally died out. 火变得微弱,最终熄灭了。"
        ],
    usageNotes: [
        "1. die of... 因...(内部原因如疾病、饥饿)而死",
        "2. die from... 因...(外部原因如事故、受伤)而死",
        "3. die out 灭绝; 熄灭",
        "4. 'die' is an instantaneous verb; cannot be used with duration phrases."
        ],
    relatedWords: ["dead(adj. 死的), death(n. 死亡), dying(adj. 垂死的)"],
  },
  {
    word: "fact",
    pronunciation: "/ fækt /",
    partOfSpeech: "n.",
    definition: "事实;真相",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "I'm going there tomorrow, as a matter of fact. 实际上我明天就要去那儿。",
        "It is a fact that the earth goes around the sun. 地球绕着太阳转是事实。"
        ],
    usageNotes: [
        "A thing that is known or proved to be true.",
        "1. in fact 事实上,实际上",
        "2. as a matter of fact 事实上,实际上",
        "face the facts 面对现实",
        ],
  },
  {
    word: "abstract",
    pronunciation: "/ 'æbstrækt /",
    partOfSpeech: "n./adj.",
    definition: "n. 概要 adj. 抽象的",
    wordRootMemory: "词根记忆: abs(离去)+tract(拉)→(将大意)从文章中拉拽出来→概要",
    examples: [
        "an abstract idea 抽象概念",
        "Beauty is an abstract concept. 美是一个抽象的概念。"
        ],
    usageNotes: [
        "Adj: Existing in thought or as an idea but not having a physical or concrete existence.",
        "Noun: A summary of the contents of a book, article, or speech.",
        "abstract art 抽象艺术",
        "in the abstract 抽象地；理论上"
        ],
  },
  {
    word: "declare",
    pronunciation: "/ dɪ'kleə(r) /",
    partOfSpeech: "vt.",
    definition: "宣布,宣告;断言,宣称; 申报(应纳税品)",
    wordRootMemory: "联想记忆: de(表加强)+clare(看作 clear,清楚)→说清楚→宣布,宣告",
    examples: [
        "Picking up her 'Lifetime Achievement' award, proud Irene declared she had no plans to retire... (2019年全国卷 2)",
        "If you have nothing to declare, go through the Green Channel. 如果你没有什么物品需要申报,请走绿色通道。"
        ],
    usageNotes: [
        "Say something in a solemn and emphatic manner.",
        "Formally announce the beginning of (a state or condition).",
        "Acknowledge possession of (taxable income or dutiable goods).",
        "declare war on sb/sth 向…宣战",
        ],
    relatedWords: ["declaration(n. 宣布；申报)"],
  },
  {
    word: "warn",
    pronunciation: "/ wɔːn /",
    partOfSpeech: "v.",
    definition: "警告;提醒",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "I have warned you of the dangerous dog. 我已经警告过你提防这条危险的狗。",
        "Mom warned little Tom not to go out alone during the night. 妈妈告诫小汤姆晚上不要一个人外出。"
        ],
    usageNotes: [
        "1. warn sb. of/about sth. 警告某人提防某事",
        "2. warn sb. not to do sth. 警告某人不要做某事",
        "3. warn sb. against doing sth. 警告某人不要做某事",
        "Inform someone in advance of a possible danger, problem, or other unpleasant situation.",
        ],
    relatedWords: ["warning(n. 警告)"],
  },

  // Page 30
  {
    word: "obey",
    pronunciation: "/ ə'beɪ /",
    partOfSpeech: "v.",
    definition: "服从,顺从,遵守",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "A soldier's duty is to obey orders. 服从命令是士兵的天职。",
        "You must obey the rules. 你必须遵守规则。"
        ],
    usageNotes: [
        "Comply with the command, direction, or request of (a person or a law).",
        "Behave in accordance with (a general principle, natural law, etc.).",
        "obey the law 遵守法律"
        ],
    relatedWords: ["disobey(v. 违抗,不服从); obedient(adj. 服从的), obedience(n. 服从)"],
  },
  {
    word: "grade",
    pronunciation: "/ greɪd /",
    partOfSpeech: "n./vt.",
    definition: "n. 等级;(中小学的)学年;成绩,分数 vt. 给…评分;给…分等级",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "Jim's elder brother will enter the sixth grade this autumn. 吉姆的哥哥今年秋季将升入六年级。(n.)",
        "You'll be graded on lab notebooks and quizzes. 将基于实验室笔记本和测验给你评分。(2017年全国卷2) (vt.)"
        ],
    usageNotes: [
        "Noun: A particular level of rank, quality, proficiency, or value.",
        "Noun: A mark indicating the quality of a student's work.",
        "Verb: Arrange in or allocate to grades; classify or sort.",
        "make the grade 达到标准"
        ],
  },
  {
    word: "fiction",
    pronunciation: "/ 'fɪkʃn /",
    partOfSpeech: "n.",
    definition: "小说;虚构的事,杜撰的事",
    wordRootMemory: "词根记忆: fict(做)+ion →造出的故事→小说",
    examples: [
        "For years he has kept writing fiction. 多年来他坚持写小说。",
        "Is the story fact or fiction? 这个故事是真实的还是虚构的？"
        ],
    usageNotes: [
        "Literature in the form of prose, especially short stories and novels, that describes imaginary events and people.",
        "Something that is invented or untrue.",
        "science fiction 科幻小说",
        "a work of fiction 一部虚构作品"
        ],
    relatedWords: ["fictional(adj. 虚构的)"],
  },
  {
    word: "expensive",
    pronunciation: "/ ɪk'spensɪv /",
    partOfSpeech: "adj.",
    definition: "昂贵的",
    wordRootMemory: "Derived from 'expense'.", // No '记' section in OCR
    examples: [
        "The house rent is expensive. 房租很贵。",
        "This watch is too expensive for me. 这块手表对我来说太贵了。"
        ],
    usageNotes: [
        "Costing a lot of money.",
        "Opposite: inexpensive, cheap.",
        "expensive tastes 昂贵的品味"
        ],
    relatedWords: ["expense(n. 花费), inexpensive(adj. 便宜的)"],
  },
  {
    word: "announce",
    pronunciation: "/ ə'naʊns /",
    partOfSpeech: "vt.",
    definition: "宣布,宣告",
    wordRootMemory: "词根记忆:an(表加强)+nounce(讲话,说出)→大声说出来→宣布,宣告",
    examples: [
        "John and Mary announced their engagement last night. 昨天晚上约翰和玛丽宣布了他们订婚的消息。",
        "The government announced a new policy. 政府宣布了一项新政策。"
        ],
    usageNotes: [
        "Make a public and typically formal declaration about a fact, occurrence, or intention.",
        "announce a decision/plan 宣布决定/计划",
        "announce sb's arrival 宣布某人到达"
        ],
    relatedWords: ["announcement(n. 公告;宣布)"],
  },
  {
    word: "nowhere",
    pronunciation: "/ 'nəʊweə(r) /",
    partOfSpeech: "adv.",
    definition: "任何地方都不;无处",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "The new novel Henry writes can be bought nowhere. 亨利写的那本新小说什么地方都买不到。",
        "I have nowhere else to go. 我无处可去。"
        ],
    usageNotes: [
        "Not in or to any place; not anywhere.",
        "Often used to indicate lack of availability or destination.",
        "get nowhere 毫无进展",
        "in the middle of nowhere 偏僻的地方"
        ],
  },
  {
    word: "persuade",
    pronunciation: "/ pə'sweɪd /",
    partOfSpeech: "vt.",
    definition: "说服,劝说;使相信",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "She persuaded me to phone the local college. 她说服我给当地的大学打电话。",
        "I try to persuade them to keep smiling. 我试图说服他们保持微笑。(2020年全国卷3)"
        ],
    usageNotes: [
        "1. persuade sb. (not) to do sth. 说服某人(不)做某事",
        "2. persuade sb. into/out of doing sth. 说服某人做/不做某事",
        "3. persuade sb. of sth. 使某人相信某事",
        "Induce (someone) to do something through reasoning or argument.",
        ],
    relatedWords: ["persuasion(n. 说服), persuasive(adj. 有说服力的)"],
  },
  {
    word: "balcony",
    pronunciation: "/ 'bælkəni /",
    partOfSpeech: "n.",
    definition: "阳台",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "We ate breakfast on the balcony at the ski lodge. 我们在滑雪场小屋的阳台上吃早餐。",
        "The apartment has a small balcony overlooking the sea. 这间公寓有一个俯瞰大海的小阳台。"
        ],
    usageNotes: [
        "A platform enclosed by a wall or balustrade on the outside of a building, with access from an upper-floor window or door.",
        "An upper floor projecting over the main floor in a theatre or hall.",
        ],
  },
  {
    word: "decision",
    pronunciation: "/ dɪ'sɪʒn /",
    partOfSpeech: "n.",
    definition: "决定;决议",
    wordRootMemory: "Derived from 'decide'.", // No '记' section in OCR
    examples: [
        "It's a difficult decision to make. 这是个艰难的决定。",
        "Have you reached a decision yet? 你做出决定了吗？"
        ],
    usageNotes: [
        "A conclusion or resolution reached after consideration.",
        "1. make a decision 做决定",
        "2. reach a decision 达成决议",
        "final decision 最终决定",
        "decision-making 决策"
        ],
    relatedWords: ["decide(v. 决定), decisive(adj. 决定性的)"],
  },

  // Page 31
  {
    word: "real",
    pronunciation: "/ rɪəl /",
    partOfSpeech: "adj.",
    definition: "真的;真实的;真正的",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "real life 现实生活",
        "a real friend 真正的朋友"
        ],
    usageNotes: [
        "Actually existing as a thing or occurring in fact; not imagined or supposed.",
        "Genuine; not imitation or artificial.",
        "real gold 真金",
        "for real (informal) 真的吗？；说真的"
        ],
    relatedWords: ["really(adv.真正地); reality(n. 真实;现实)"],
  },
  {
    word: "seldom",
    pronunciation: "/ 'seldəm /",
    partOfSpeech: "adv.",
    definition: "很少,不常",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "He seldom cries, does he? 他很少哭,是吗?",
        "Seldom did I ask him for help. 我很少向他求助。"
        ],
    usageNotes: [
        "Not often; rarely.",
        "Negative adverb: requires inversion when placed at the beginning of a sentence.",
        "Often contrasted with 'often', 'always', 'sometimes'.",
        "Compare 'seldom' (frequency) and 'hardly' (degree/ability)."
        ],
  },
  {
    word: "circumstance",
    pronunciation: "/ 'sɜːkəmstəns /",
    partOfSpeech: "n.",
    definition: "环境;情况",
    wordRootMemory: "词根记忆:circum(周围)+stance(站)→周围存在的事物→环境",
    examples: [
        "The circumstances forced me to accept it. 迫于环境的压力,我不得不接受。",
        "Under normal circumstances, the train arrives on time. 在正常情况下，火车会准时到达。"
        ],
    usageNotes: [
        "A fact or condition connected with or relevant to an event or action.",
        "Often used in plural: circumstances.",
        "under/in the circumstances 在这种情况下",
        "due to/owing to circumstances beyond our control 由于不可控因素"
        ],
  },
  {
    word: "need",
    pronunciation: "/ niːd /",
    partOfSpeech: "vt./modal v./n.",
    definition: "vt. 需要 modal v. 必须 n. 需要,需求",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "Need you go now? -No, I needn't. / Yes, I must. 你现在必须走吗? -不,不必。/是的,必须走。(modal)",
        "You don't need to describe her, because I have met her several times. 你不用给我形容她长什么样子,我已经见过她好几次了。(vt.)"
        ],
    usageNotes: [
        "1. Modal verb: used mainly in negative and interrogative sentences.",
        "2. needn't have done... 本不必做…(实际已做)",
        "3. Main verb: need + to do / need + noun.",
        "4. need + doing / need + to be done (passive meaning, subject is thing)."
        ],
    relatedWords: ["needs(n. pl. 需求), needy(adj. 贫穷的)"],
  },
  {
    word: "spot",
    pronunciation: "/ spɒt /",
    partOfSpeech: "n./vt.",
    definition: "n. 斑点,污点;场所,地点 vt. (spotted, spotted, spotting)认出,发现",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "I want to know whether the thief was caught on the spot. 我想知道这个贼是否当场被抓住了。(n.)",
        "Nicolo spotted two paintings he thought would look nice above his dining room table. (2020年全国卷2) (vt.)"
        ],
    usageNotes: [
        "Noun: A small round or roundish mark, differing in colour or texture from the surface around it.",
        "Noun: A particular place or point.",
        "Verb: See, notice, or recognize (someone or something) that is difficult to detect or that one is searching for.",
        "on the spot 当场; 在现场; 在原地"
        ],
    relatedWords: ["spotless(adj. 无瑕疵的)"],
  },

  // Page 32
  {
    word: "bakery",
    pronunciation: "/ 'beɪkəri /",
    partOfSpeech: "n.",
    definition: "面包店",
    wordRootMemory: "词根记忆:bake(烘烤)+ry→面包店",
    examples: [
        "It is very busy at the bakery before sunrise. 日出前,面包房里很繁忙。",
        "I bought some fresh bread from the bakery. 我从面包店买了一些新鲜面包。"
        ],
    usageNotes: [
        "A place where bread and cakes are made or sold.",
        "Go to the bakery 去面包店"
        ],
    relatedWords: ["bake(v. 烘烤), baker(n. 面包师)"],
  },
  {
    word: "anyway",
    pronunciation: "/ 'eniweɪ /",
    partOfSpeech: "adv.",
    definition: "不管怎样;反正",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "This idea probably won't work, but let's try it anyway. 这个想法可能行不通,但无论如何我们都要试一试。",
        "It's too late, anyway. 反正现在已经太迟了。"
        ],
    usageNotes: [
        "Used to confirm or support a point or idea just mentioned.",
        "Used to end a conversation, resume a story, or change the subject.",
        "Regardless; anyhow.",
        "Synonyms: anyhow, in any case, nevertheless."
        ],
  },
  {
    word: "punish",
    pronunciation: "/ 'pʌnɪʃ /",
    partOfSpeech: "vt.",
    definition: "惩罚,处罚",
    wordRootMemory: "联想记忆:因为没有完成 (finish) 任务受到惩罚 (punish)",
    examples: [
        "His parents punished him for coming home late. 因为回家晚了,他的父母惩罚了他。",
        "The teacher punished the student for cheating. 老师因学生作弊而处罚了他。"
        ],
    usageNotes: [
        "Inflict a penalty or sanction on (someone) as retribution for an offence.",
        "punish sb for sth 因某事惩罚某人",
        ],
    relatedWords: ["punishment(n. 惩罚)"],
  },
  {
    word: "challenge",
    pronunciation: "/ 'tʃælɪndʒ /",
    partOfSpeech: "n./vt.",
    definition: "n. [C]挑战;质疑 vt. 挑战",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "He challenged me to play another tennis game. 他向我挑战,邀我再跟他打一场网球赛。(vt.)",
        "Finding common ground in communication style can be a challenge. (2020年全国卷 2) (n.)"
        ],
    usageNotes: [
        "1. challenge sb. to do sth. 挑战某人做某事;邀请某人比赛",
        "2. challenge sb. to sth. 挑战某人做某事",
        "3. issue/give a challenge 发起挑战",
        "4. accept/take a challenge 接受挑战",
        ],
    relatedWords: ["challenging(adj. 有挑战性的), challenger(n. 挑战者)"],
  },
  {
    word: "situation",
    pronunciation: "/ ˌsɪtʃu'eɪʃn /",
    partOfSpeech: "n. [C]",
    definition: "形势,情况",
    wordRootMemory: "Derived from 'situate'.", // No '记' section in OCR
    examples: [
        "a dangerous situation 危险的境地",
        "I know I can act under pressure in a scary situation. (2017年北京卷)"
        ],
    usageNotes: [
        "A set of circumstances in which one finds oneself; a state of affairs.",
        "The location and surroundings of a place.",
        "in a difficult situation 处境困难",
        "assess the situation 评估形势"
        ],
  },
  {
    word: "extraordinary",
    pronunciation: "/ ɪk'strɔːdnri /",
    partOfSpeech: "adj.",
    definition: "非常的;非凡的",
    wordRootMemory: "词根记忆:extra(以外)+ordinary(平常的)→平常之外的→非凡的",
    examples: [
        "extraordinary situations 特殊情况",
        "extraordinary achievements 非凡的成就"
        ],
    usageNotes: [
        "Very unusual or remarkable.",
        "Beyond the usual or ordinary.",
        "extraordinary talent 非凡的才能",
        "extraordinary circumstances 特殊情况"
        ],
    relatedWords: ["ordinary(adj. 普通的)"],
  },
  {
    word: "frost",
    pronunciation: "/ frɒst /",
    partOfSpeech: "n. [U]",
    definition: "霜",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "The grass was covered with frost. 草被霜覆盖着。",
        "There was a hard frost last night. 昨晚下了很重的霜。"
        ],
    usageNotes: [
        "A thin layer of ice on a solid surface, which forms when water vapour in the air comes into contact with a surface whose temperature is below freezing.",
        "Weather conditions that favour the formation of frost.",
        "frost damage 霜冻损害"
        ],
    relatedWords: ["frosty(adj. 结霜的；寒冷的)"],
  },

  // Page 33
  {
    word: "abrupt",
    pronunciation: "/ ə'brʌpt /",
    partOfSpeech: "adj.",
    definition: "突然的,意外的;唐突的",
    wordRootMemory: "词根记忆:ab(离去)+rupt(断)→突然断掉了→突然的,意外的",
    examples: [
        "The outbreak of Covid-19 has meant an abrupt change in our life and work. (2020 年江苏卷)",
        "He made an abrupt departure. 他突然离开了。"
        ],
    usageNotes: [
        "Sudden and unexpected.",
        "Brief to the point of rudeness; curt.",
        "an abrupt manner 唐突的态度"
        ],
    relatedWords: ["abruptly(adv. 突然地)"],
  },
  {
    word: "convince",
    pronunciation: "/ kən'vɪns /",
    partOfSpeech: "vt.",
    definition: "使确信,使信服",
    wordRootMemory: "词根记忆:con(表加强)+vince(征服)→彻底征服对方→使信服",
    examples: [
        "What can I do to convince you of the truth? 我要怎么做才能让你相信这是事实?",
        "He convinced me that the story was true. 他使我相信那个故事是真的。"
        ],
    usageNotes: [
        "Cause (someone) to believe firmly in the truth of something.",
        "Persuade (someone) to do something.",
        "convince sb of sth 使某人相信某事",
        "convince sb that... 使某人相信..."
        ],
    relatedWords: ["convinced(adj. 确信的), convincing(adj. 有说服力的)"],
  },
  {
    word: "shock",
    pronunciation: "/ ʃɒk /",
    partOfSpeech: "vt./n.",
    definition: "vt. 使震惊 n. 震动,冲击",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "shock wave 冲击波",
        "The news came as a great shock to everyone. 这个消息让所有人都大为震惊。(n.)"
        ],
    usageNotes: [
        "Noun: A sudden upsetting or surprising event or experience.",
        "Noun: A violent shaking movement caused by an impact, explosion, or earthquake.",
        "Verb: Cause (someone) to feel surprised and upset.",
        "in shock 处于震惊状态"
        ],
    relatedWords: ["shocking(adj.令人震惊的;令人厌恶的;非常糟糕的); shocked(adj. 感到震惊的)"],
  },
  {
    word: "slight",
    pronunciation: "/ slaɪt /",
    partOfSpeech: "adj.",
    definition: "轻微的,细小的",
    wordRootMemory: "联想记忆:s+light(轻的) →轻微的",
    examples: [
        "slight mistake 微小的错误",
        "slight movement 轻微的运动"
        ],
    usageNotes: [
        "Small in degree; inconsiderable.",
        "(Of a person or their build) slim; slender.",
        "a slight headache 轻微头痛",
        "not in the slightest 一点也不"
        ],
    relatedWords: ["slightly(adv. 轻微地)"],
  },
  {
    word: "dessert",
    pronunciation: "/ dɪ'zɜːt /",
    partOfSpeech: "n.",
    definition: "甜点,(餐后)甜食",
    wordRootMemory: "联想记忆:在沙漠 (desert) 中吃不到美味的甜点(dessert)",
    examples: [
        "Western people have the custom of eating dessert after meals. 西方人有饭后吃甜点的习惯。",
        "What's for dessert? 甜点是什么？"
        ],
    usageNotes: [
        "The sweet course eaten at the end of a meal.",
        "Often confused with 'desert' (arid land).",
        "fruit dessert 水果甜点",
        ],
  },
  {
    word: "unfair",
    pronunciation: "/ ˌʌn'feə(r) /",
    partOfSpeech: "adj.",
    definition: "不公平的,不公正的",
    wordRootMemory: "词根记忆:un(不)+fair(公平的,公正的)→不公平的,不公正的",
    examples: [
        "This is unfair. 这不公平。",
        "It's unfair to blame him for everything. 把一切都归咎于他是不公平的。"
        ],
    usageNotes: [
        "Not based on or behaving according to the principles of equality and justice.",
        "Opposite: fair.",
        "unfair advantage 不公平的优势",
        "unfair treatment 不公平待遇"
        ],
    relatedWords: ["unfairly(adv. 不公正地)"],
  },
  {
    word: "on",
    pronunciation: "/ ɒn /",
    partOfSpeech: "prep./adv.",
    definition: "prep. 在…上; 在…时候; 在…地方;关于 adv. 继续",
    wordRootMemory: "", // No '记' section in OCR
    examples: [
        "On his arrival, I told him what had happened. 他一到,我就告诉他发生了什么事情。",
        "The book is on the table. 书在桌子上。"
        ],
    usageNotes: [
        "1. on the moment 立刻",
        "2. on time 按时,准时",
        "3. on holiday/vacation 在度假",
        "4. on the other hand 另一方面",
        // "5. on the contrary 正相反",
        // "6. on the/one's way (to) 在(去)…的路上",
        // "7. on the whole 基本上,大体上",
        // "8. on show 在展出",
        // "9. on and on 继续不停地",
        // "10. on duty 值班;上班",
        // "11. on one's own 独立地,自主地",
        // "12. on foot 步行" // Reduced notes due to 4-line limit
        ],
  },
];